[build]
  command = "npm run build"
  publish = "dist"

# Disable the Next.js plugin since this is a Vite project
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disable = true 