[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Disable framework detection to prevent conflicts
[build.processing]
  skip_processing = false

# Ensure we're using Node.js runtime only
[context.production.environment]
  NODE_ENV = "production" 